export const HTTP_STATUS_CODES: { code: string; name: string; description: string }[] = [
  { code: "200", name: "OK", description: "リクエストが成功しました。" },
  { code: "201", name: "Created", description: "リクエストが成功し、新しいリソースが作成されました。" },
  { code: "204", name: "No Content", description: "リクエストは成功しましたが、返す内容がありません。" },
  { code: "301", name: "Moved Permanently", description: "リソースが恒久的に移動しました。" },
  { code: "302", name: "Found", description: "リソースが一時的に別のURLにあります。" },
  { code: "304", name: "Not Modified", description: "リソースは変更されていません(キャッシュ利用可)。" },
  { code: "400", name: "Bad Request", description: "リクエストの構文が不正です。" },
  { code: "401", name: "Unauthorized", description: "認証が必要です。" },
  { code: "403", name: "Forbidden", description: "アクセスが禁止されています。" },
  { code: "404", name: "Not Found", description: "リソースが見つかりません。" },
  { code: "405", name: "Method Not Allowed", description: "許可されていないHTTPメソッドです。" },
  { code: "408", name: "Request Timeout", description: "リクエストがタイムアウトしました。" },
  { code: "409", name: "Conflict", description: "リクエストがサーバーの現在の状態と競合しています。" },
  { code: "410", name: "Gone", description: "リソースが恒久的に削除されました。" },
  { code: "418", name: "I'm a teapot", description: "サーバーはティーポットであるため要求を実行できません(ジョークステータス)。" },
  { code: "422", name: "Unprocessable Entity", description: "リクエストの形式は正しいが意味的エラーがあります。" },
  { code: "429", name: "Too Many Requests", description: "一定時間内のリクエスト数が多すぎます。" },
  { code: "500", name: "Internal Server Error", description: "サーバー内部でエラーが発生しました。" },
  { code: "502", name: "Bad Gateway", description: "ゲートウェイまたはプロキシが不正な応答を受け取りました。" },
  { code: "503", name: "Service Unavailable", description: "サーバーが一時的に利用できません。" },
  { code: "504", name: "Gateway Timeout", description: "ゲートウェイまたはプロキシがタイムアウトしました。" },
];
