export const MIME_TYPES: { code: string; name: string; description: string }[] = [
  { code: ".html", name: "text/html", description: "HTML文書" },
  { code: ".css", name: "text/css", description: "スタイルシート" },
  { code: ".js", name: "text/javascript", description: "JavaScript" },
  { code: ".json", name: "application/json", description: "JSON形式データ" },
  { code: ".xml", name: "application/xml", description: "XML形式データ" },
  { code: ".pdf", name: "application/pdf", description: "PDF文書" },
  { code: ".zip", name: "application/zip", description: "ZIP圧縮ファイル" },
  { code: ".png", name: "image/png", description: "PNG画像" },
  { code: ".jpg / .jpeg", name: "image/jpeg", description: "JPEG画像" },
  { code: ".gif", name: "image/gif", description: "GIF画像" },
  { code: ".svg", name: "image/svg+xml", description: "SVG画像" },
  { code: ".webp", name: "image/webp", description: "WebP画像" },
  { code: ".ico", name: "image/x-icon", description: "アイコンファイル" },
  { code: ".mp3", name: "audio/mpeg", description: "MP3音声" },
  { code: ".wav", name: "audio/wav", description: "WAV音声" },
  { code: ".mp4", name: "video/mp4", description: "MP4動画" },
  { code: ".webm", name: "video/webm", description: "WebM動画" },
  { code: ".txt", name: "text/plain", description: "プレーンテキスト" },
  { code: ".csv", name: "text/csv", description: "CSVファイル" },
  { code: ".woff2", name: "font/woff2", description: "Webフォント(WOFF2)" },
  { code: ".ttf", name: "font/ttf", description: "TrueTypeフォント" },
  { code: ".doc / .docx", name: "application/msword", description: "Word文書" },
  { code: ".xls / .xlsx", name: "application/vnd.ms-excel", description: "Excel表計算" },
];
