import type { CategoryDefinition, ToolDefinition } from "./types";

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: "text",
    name: "テキスト処理",
    description: "文字数カウントや大文字小文字変換など、文章の編集・整形に役立つツール",
    section: "tools",
  },
  {
    id: "encode",
    name: "エンコード/デコード",
    description: "Base64やURLエンコードなど、データ形式の変換・生成ツール",
    section: "tools",
  },
  {
    id: "calc",
    name: "数値・計算",
    description: "電卓やBMI計算など、日常のちょっとした計算に使えるツール",
    section: "tools",
  },
  {
    id: "unit",
    name: "単位変換",
    description: "長さ・重さ・温度など、単位を相互変換するツール",
    section: "tools",
  },
  {
    id: "datetime",
    name: "日付・時間",
    description: "タイムスタンプ変換やタイマーなど、日付・時間に関するツール",
    section: "tools",
  },
  {
    id: "color",
    name: "色・デザイン",
    description: "カラーコード変換やパレット生成など、デザイン作業に役立つツール",
    section: "tools",
  },
  {
    id: "dev",
    name: "開発者ツール",
    description: "JSON整形やMarkdownプレビューなど、開発者向けのツール",
    section: "tools",
  },
  {
    id: "life",
    name: "生活・お金",
    description: "カロリー計算や時給計算など、暮らしに役立つ簡易計算ツール",
    section: "tools",
  },
  {
    id: "midgame",
    name: "ミドルゲーム",
    description: "2048やスネークゲームなど、少し遊び込めるブラウザゲーム",
    section: "games",
  },
  {
    id: "random",
    name: "ミニゲーム・ランダム",
    description: "サイコロやくじ引きなど、ランダム性を使った手軽なミニゲーム・ツール",
    section: "games",
  },
];

export const ALL_TOOLS: ToolDefinition[] = [
  // --- テキスト処理 (20) ---
  { slug: "char-count", name: "文字数・単語数カウント", description: "入力した文章の文字数・単語数・行数をリアルタイムで表示します。", category: "text", componentKey: "text-counter", keywords: ["文字数", "文字カウント", "word count"] },
  { slug: "uppercase", name: "大文字変換", description: "英字をすべて大文字に変換します。", category: "text", componentKey: "case-converter", config: { mode: "upper" }, keywords: ["uppercase", "大文字"] },
  { slug: "lowercase", name: "小文字変換", description: "英字をすべて小文字に変換します。", category: "text", componentKey: "case-converter", config: { mode: "lower" }, keywords: ["lowercase", "小文字"] },
  { slug: "titlecase", name: "タイトルケース変換", description: "各単語の先頭を大文字にするタイトルケースに変換します。", category: "text", componentKey: "case-converter", config: { mode: "title" }, keywords: ["title case"] },
  { slug: "camelcase", name: "キャメルケース変換", description: "文字列をcamelCase形式に変換します。", category: "text", componentKey: "case-converter", config: { mode: "camel" }, keywords: ["camelCase", "プログラミング"] },
  { slug: "snakecase", name: "スネークケース変換", description: "文字列をsnake_case形式に変換します。", category: "text", componentKey: "case-converter", config: { mode: "snake" }, keywords: ["snake_case"] },
  { slug: "kebabcase", name: "ケバブケース変換", description: "文字列をkebab-case形式に変換します。", category: "text", componentKey: "case-converter", config: { mode: "kebab" }, keywords: ["kebab-case"] },
  { slug: "pascalcase", name: "パスカルケース変換", description: "文字列をPascalCase形式に変換します。", category: "text", componentKey: "case-converter", config: { mode: "pascal" }, keywords: ["PascalCase"] },
  { slug: "fullwidth-halfwidth", name: "全角⇔半角変換", description: "英数字・記号の全角と半角を相互に変換します。", category: "text", componentKey: "width-converter", keywords: ["全角", "半角"] },
  { slug: "hiragana-katakana", name: "ひらがな⇔カタカナ変換", description: "ひらがなとカタカナを相互に変換します。", category: "text", componentKey: "kana-converter", keywords: ["ひらがな", "カタカナ"] },
  { slug: "whitespace-cleanup", name: "空白・改行整形", description: "余分な空白や連続する改行をまとめて削除・整形します。", category: "text", componentKey: "whitespace-cleaner", keywords: ["trim", "空白削除"] },
  { slug: "line-sort", name: "行の並び替え", description: "複数行のテキストを昇順・降順・ランダムに並び替えます。", category: "text", componentKey: "line-sorter", keywords: ["sort", "ソート"] },
  { slug: "line-dedup", name: "重複行削除", description: "テキスト内の重複した行を削除します。", category: "text", componentKey: "line-dedup", keywords: ["重複削除", "unique"] },
  { slug: "line-numbering", name: "行番号付与", description: "各行の先頭に連番の行番号を付けます。", category: "text", componentKey: "line-numberer", keywords: ["行番号"] },
  { slug: "text-reverse", name: "文字列反転", description: "文字列を逆順に並び替えます。", category: "text", componentKey: "text-reverser", keywords: ["reverse", "反転"] },
  { slug: "text-diff", name: "テキスト差分比較", description: "2つのテキストを行単位で比較し、差分をハイライト表示します。", category: "text", componentKey: "diff-checker", keywords: ["diff", "差分"] },
  { slug: "regex-tester", name: "正規表現テスター", description: "正規表現パターンをテキストに適用し、マッチ結果を確認できます。", category: "text", componentKey: "regex-tester", keywords: ["regex", "正規表現"] },
  { slug: "lorem-ipsum", name: "ダミーテキスト生成", description: "デザインや原稿確認用のダミーテキスト(日本語/Lorem Ipsum)を生成します。", category: "text", componentKey: "lorem-generator", keywords: ["lorem ipsum", "ダミー"] },
  { slug: "slug-generator", name: "スラッグ生成", description: "文字列をURLスラッグ(半角英数とハイフン)に変換します。", category: "text", componentKey: "slug-generator", keywords: ["slug", "url"] },
  { slug: "char-frequency", name: "文字出現頻度カウント", description: "テキスト内に出現する文字の頻度を集計します。", category: "text", componentKey: "char-frequency", keywords: ["頻度", "集計"] },
  { slug: "alternating-case", name: "交互大文字変換", description: "文字を1文字ごとに大文字・小文字交互に変換します(aLtErNaTiNg)。", category: "text", componentKey: "case-converter", config: { mode: "alternating" }, keywords: ["alternating case"] },
  { slug: "inverse-case", name: "大文字小文字反転", description: "大文字と小文字を入れ替えます。", category: "text", componentKey: "case-converter", config: { mode: "inverse" }, keywords: ["inverse case"] },
  { slug: "sentence-case", name: "文章的大文字変換(Sentence case)", description: "文の先頭のみを大文字にするSentence caseに変換します。", category: "text", componentKey: "case-converter", config: { mode: "sentence" }, keywords: ["sentence case"] },
  { slug: "constant-case", name: "定数名変換(CONSTANT_CASE)", description: "文字列をCONSTANT_CASE形式に変換します。", category: "text", componentKey: "case-converter", config: { mode: "constant" }, keywords: ["constant case", "定数"] },
  { slug: "train-case", name: "トレインケース変換(Train-Case)", description: "文字列をTrain-Case形式に変換します。", category: "text", componentKey: "case-converter", config: { mode: "train" }, keywords: ["train case"] },
  { slug: "html-tag-stripper", name: "HTMLタグ除去", description: "テキストからHTMLタグを取り除きます。", category: "text", componentKey: "html-tag-stripper", keywords: ["html", "タグ除去"] },
  { slug: "punctuation-remover", name: "句読点・記号除去", description: "テキストから句読点や記号を取り除きます。", category: "text", componentKey: "punctuation-remover", keywords: ["句読点", "記号除去"] },
  { slug: "digit-remover", name: "数字除去", description: "テキストから数字だけを取り除きます。", category: "text", componentKey: "digit-remover", keywords: ["数字除去"] },
  { slug: "emoji-remover", name: "絵文字除去", description: "テキストから絵文字を取り除きます。", category: "text", componentKey: "emoji-remover", keywords: ["絵文字除去"] },
  { slug: "leetspeak-converter", name: "リートスピーク変換", description: "アルファベットを数字に置き換えるリートスピーク(1337speak)に変換します。", category: "text", componentKey: "leetspeak-converter", keywords: ["leetspeak", "1337"] },
  { slug: "upside-down-text", name: "逆さ文字変換", description: "文字を上下逆さまに見えるUnicode文字に変換します。", category: "text", componentKey: "upside-down-text", keywords: ["upside down"] },
  { slug: "whitespace-visualizer", name: "空白可視化ツール", description: "スペース・タブ・改行を記号で可視化して表示します。", category: "text", componentKey: "whitespace-visualizer", keywords: ["空白可視化"] },
  { slug: "morse-code", name: "モールス信号変換", description: "テキストとモールス信号を相互に変換します。", category: "text", componentKey: "morse-code-tool", keywords: ["モールス信号", "morse"] },
  { slug: "nato-phonetic", name: "NATOフォネティックコード変換", description: "文字とNATOフォネティックコード(Alpha, Bravoなど)を相互に変換します。", category: "text", componentKey: "nato-phonetic-tool", keywords: ["nato", "フォネティック"] },
  { slug: "tab-space-converter", name: "タブ・スペース変換", description: "タブ文字と半角スペースを相互に変換します。", category: "text", componentKey: "tab-space-converter", keywords: ["タブ", "スペース"] },
  { slug: "palindrome-checker", name: "回文チェッカー", description: "入力した文字列が回文かどうかを判定します。", category: "text", componentKey: "palindrome-checker", keywords: ["回文", "palindrome"] },
  { slug: "anagram-checker", name: "アナグラムチェッカー", description: "2つの文字列がアナグラム(文字の並び替え)かどうかを判定します。", category: "text", componentKey: "anagram-checker", keywords: ["アナグラム", "anagram"] },
  { slug: "reading-time-estimator", name: "読了時間推定", description: "文章の文字数・単語数からおおよその読了時間を推定します。", category: "text", componentKey: "reading-time-estimator", keywords: ["読了時間"] },
  { slug: "sentence-counter", name: "文の数カウント", description: "テキスト内の文の数をカウントします。", category: "text", componentKey: "single-stat-counter", config: { stat: "sentence" }, keywords: ["文の数"] },
  { slug: "paragraph-counter", name: "段落数カウント", description: "テキスト内の段落数をカウントします。", category: "text", componentKey: "single-stat-counter", config: { stat: "paragraph" }, keywords: ["段落数"] },
  { slug: "url-extractor", name: "URL抽出", description: "テキストに含まれるURLを一覧抽出します。", category: "text", componentKey: "list-extractor", config: { extractor: "url" }, keywords: ["url抽出"] },
  { slug: "email-extractor", name: "メールアドレス抽出", description: "テキストに含まれるメールアドレスを一覧抽出します。", category: "text", componentKey: "list-extractor", config: { extractor: "email" }, keywords: ["メールアドレス抽出"] },
  { slug: "string-padding", name: "文字列パディング", description: "指定した文字数になるように文字列の前後を指定文字で埋めます。", category: "text", componentKey: "string-padding-tool", keywords: ["パディング", "padding"] },
  { slug: "text-repeater", name: "テキスト繰り返し生成", description: "指定したテキストを指定回数繰り返して生成します。", category: "text", componentKey: "text-repeater", keywords: ["繰り返し"] },

  // --- エンコード/デコード (12) ---
  { slug: "base64", name: "Base64エンコード/デコード", description: "テキストをBase64形式に変換・復元します。", category: "encode", componentKey: "base64-tool", keywords: ["base64"] },
  { slug: "url-encode", name: "URLエンコード/デコード", description: "テキストをURLエンコード・デコードします。", category: "encode", componentKey: "url-encode-tool", keywords: ["url encode", "percent encoding"] },
  { slug: "html-entity", name: "HTMLエンティティエンコード/デコード", description: "特殊文字をHTMLエンティティに変換・復元します。", category: "encode", componentKey: "html-entity-tool", keywords: ["html entity"] },
  { slug: "hex-encode", name: "16進数(Hex)エンコード/デコード", description: "テキストと16進数表現を相互に変換します。", category: "encode", componentKey: "hex-tool", keywords: ["hex", "16進数"] },
  { slug: "binary-text", name: "2進数(Binary)テキスト変換", description: "テキストと2進数表現を相互に変換します。", category: "encode", componentKey: "binary-tool", keywords: ["binary", "2進数"] },
  { slug: "rot13", name: "ROT13変換", description: "アルファベットを13文字分シフトするROT13で変換します。", category: "encode", componentKey: "rot13-tool", keywords: ["rot13"] },
  { slug: "jwt-decode", name: "JWTデコーダー", description: "JWTトークンのヘッダーとペイロードをデコードして表示します。", category: "encode", componentKey: "jwt-decoder", keywords: ["jwt", "json web token"] },
  { slug: "uuid-generator", name: "UUID生成", description: "ランダムなUUID(v4)を生成します。", category: "encode", componentKey: "uuid-generator", keywords: ["uuid", "guid"] },
  { slug: "qrcode-generator", name: "QRコード生成", description: "テキストやURLからQRコード画像を生成します。", category: "encode", componentKey: "qr-generator", keywords: ["qr code", "qrコード"] },
  { slug: "wifi-qrcode", name: "Wi-Fi QRコード生成", description: "Wi-Fi接続情報を読み取るとすぐに接続できるQRコードを生成します。", category: "encode", componentKey: "wifi-qr-generator", keywords: ["wifi", "qr"] },
  { slug: "password-generator", name: "パスワード生成", description: "条件を指定してランダムなパスワードを生成します。", category: "encode", componentKey: "password-generator", keywords: ["password", "パスワード"] },
  { slug: "linebreak-convert", name: "改行コード変換", description: "LF・CRLF・CRの改行コードを相互に変換します。", category: "encode", componentKey: "linebreak-converter", keywords: ["改行コード", "lf", "crlf"] },
  { slug: "base32", name: "Base32エンコード/デコード", description: "テキストをBase32形式に変換・復元します。", category: "encode", componentKey: "base32-tool", keywords: ["base32"] },
  { slug: "base58", name: "Base58エンコード/デコード", description: "テキストをBase58形式に変換・復元します。", category: "encode", componentKey: "base58-tool", keywords: ["base58"] },
  { slug: "base85", name: "Base85(ASCII85)エンコード/デコード", description: "テキストをBase85(ASCII85)形式に変換・復元します。", category: "encode", componentKey: "base85-tool", keywords: ["base85", "ascii85"] },
  { slug: "caesar-cipher", name: "シーザー暗号", description: "指定したシフト数でアルファベットをずらして暗号化・復号します。", category: "encode", componentKey: "caesar-cipher-tool", keywords: ["シーザー暗号", "caesar"] },
  { slug: "vigenere-cipher", name: "ヴィジュネル暗号", description: "キーワードを使ってアルファベットを暗号化・復号するヴィジュネル暗号です。", category: "encode", componentKey: "vigenere-cipher-tool", keywords: ["ヴィジュネル暗号", "vigenere"] },
  { slug: "md5-hash", name: "MD5ハッシュ生成", description: "テキストからMD5ハッシュ値を生成します。", category: "encode", componentKey: "hash-generator", config: { algo: "MD5" }, keywords: ["md5", "ハッシュ"] },
  { slug: "sha1-hash", name: "SHA-1ハッシュ生成", description: "テキストからSHA-1ハッシュ値を生成します。", category: "encode", componentKey: "hash-generator", config: { algo: "SHA-1" }, keywords: ["sha1", "ハッシュ"] },
  { slug: "sha256-hash", name: "SHA-256ハッシュ生成", description: "テキストからSHA-256ハッシュ値を生成します。", category: "encode", componentKey: "hash-generator", config: { algo: "SHA-256" }, keywords: ["sha256", "ハッシュ"] },
  { slug: "sha512-hash", name: "SHA-512ハッシュ生成", description: "テキストからSHA-512ハッシュ値を生成します。", category: "encode", componentKey: "hash-generator", config: { algo: "SHA-512" }, keywords: ["sha512", "ハッシュ"] },
  { slug: "punycode", name: "Punycode変換", description: "国際化ドメイン名(IDN)とPunycode(ACE形式)を相互に変換します。", category: "encode", componentKey: "punycode-tool", keywords: ["punycode", "idn", "ドメイン"] },
  { slug: "csv-escape", name: "CSVエスケープ/アンエスケープ", description: "CSVフィールドのエスケープ・アンエスケープを行います。", category: "encode", componentKey: "csv-escape-tool", keywords: ["csv", "エスケープ"] },
  { slug: "data-url-encoder", name: "Data URLエンコーダー", description: "画像・ファイルをBase64形式のData URLに変換します。", category: "encode", componentKey: "data-url-encoder", keywords: ["data url", "base64", "画像"] },

  // --- 数値・計算 (18) ---
  { slug: "base-convert", name: "進数変換", description: "2進数・8進数・10進数・16進数を相互に変換します。", category: "calc", componentKey: "base-number-converter", keywords: ["進数変換"] },
  { slug: "calculator", name: "電卓", description: "四則演算ができるシンプルな電卓です。", category: "calc", componentKey: "calculator", keywords: ["電卓", "計算"] },
  { slug: "sqrt-pow", name: "平方根・累乗計算機", description: "平方根・n乗・累乗根を計算します。", category: "calc", componentKey: "sqrt-pow-calculator", keywords: ["平方根", "累乗"] },
  { slug: "bmi", name: "BMI計算機", description: "身長と体重からBMIと判定区分を計算します。", category: "calc", componentKey: "bmi-calculator", keywords: ["bmi", "肥満度"] },
  { slug: "age-calculator", name: "年齢計算機", description: "生年月日から現在の年齢を計算します。", category: "calc", componentKey: "age-calculator", keywords: ["年齢計算"] },
  { slug: "percentage", name: "パーセンテージ計算機", description: "割合・増減率などパーセンテージに関する計算をまとめて行えます。", category: "calc", componentKey: "percentage-calculator", keywords: ["割合", "パーセント"] },
  { slug: "warikan", name: "割り勘計算機", description: "合計金額を人数で割り勘計算します。", category: "calc", componentKey: "warikan-calculator", keywords: ["割り勘"] },
  { slug: "tax-calculator", name: "消費税計算機", description: "税抜き・税込み価格と消費税額を計算します。", category: "calc", componentKey: "tax-calculator", keywords: ["消費税", "税込"] },
  { slug: "gcd-lcm", name: "最大公約数・最小公倍数", description: "2つ以上の整数の最大公約数と最小公倍数を計算します。", category: "calc", componentKey: "gcd-lcm-calculator", keywords: ["gcd", "lcm"] },
  { slug: "prime-factorization", name: "素因数分解", description: "整数を入力して素因数分解します。", category: "calc", componentKey: "prime-factorization", keywords: ["素因数分解"] },
  { slug: "circle-calculator", name: "円の面積・円周計算機", description: "半径から円の面積と円周を計算します。", category: "calc", componentKey: "circle-calculator", keywords: ["円の面積"] },
  { slug: "triangle-area", name: "三角形の面積計算機", description: "底辺と高さ、または3辺の長さから三角形の面積を計算します。", category: "calc", componentKey: "triangle-calculator", keywords: ["三角形の面積"] },
  { slug: "compound-interest", name: "複利計算機", description: "元本・利率・期間から複利の将来価値を計算します。", category: "calc", componentKey: "compound-interest-calculator", keywords: ["複利"] },
  { slug: "loan-calculator", name: "ローン返済計算機", description: "借入額・金利・返済期間から毎月の返済額を計算します。", category: "calc", componentKey: "loan-calculator", keywords: ["ローン", "返済"] },
  { slug: "exchange-calculator", name: "為替電卓", description: "手動で設定した為替レートで通貨換算します。", category: "calc", componentKey: "exchange-calculator", keywords: ["為替", "通貨換算"] },
  { slug: "tip-calculator", name: "チップ計算機", description: "会計金額とチップ率から支払額・チップ額を計算します。", category: "calc", componentKey: "tip-calculator", keywords: ["チップ"] },
  { slug: "stats-calculator", name: "統計計算機", description: "数値リストの平均・中央値・分散・標準偏差を計算します。", category: "calc", componentKey: "stats-calculator", keywords: ["平均", "標準偏差"] },
  { slug: "fraction-calculator", name: "分数計算機", description: "分数の加減乗除を計算し、既約分数で表示します。", category: "calc", componentKey: "fraction-calculator", keywords: ["分数"] },
  { slug: "quadratic-equation", name: "二次方程式計算機", description: "ax²+bx+c=0の形の二次方程式を解きます。", category: "calc", componentKey: "quadratic-equation-calculator", keywords: ["二次方程式"] },
  { slug: "permutation-combination", name: "順列・組み合わせ計算機", description: "nPr(順列)とnCr(組み合わせ)を計算します。", category: "calc", componentKey: "permutation-combination-calculator", keywords: ["順列", "組み合わせ"] },
  { slug: "matrix-2x2", name: "2×2行列計算機", description: "2×2行列の行列式・トレース・逆行列を計算します。", category: "calc", componentKey: "matrix-2x2-calculator", keywords: ["行列", "matrix"] },
  { slug: "roman-numeral", name: "ローマ数字変換", description: "数値とローマ数字を相互に変換します。", category: "calc", componentKey: "roman-numeral-converter", keywords: ["ローマ数字"] },
  { slug: "leap-year-checker", name: "うるう年判定", description: "指定した年がうるう年かどうかを判定します。", category: "calc", componentKey: "leap-year-checker", keywords: ["うるう年"] },
  { slug: "gpa-calculator", name: "成績平均(GPA)計算機", description: "評価と単位数からGPA(成績平均値)を計算します。", category: "calc", componentKey: "gpa-calculator", keywords: ["gpa", "成績"] },
  { slug: "unit-price-comparator", name: "単価比較計算機", description: "2つの商品の単価を比較してどちらがお得か判定します。", category: "calc", componentKey: "unit-price-comparator", keywords: ["単価比較"] },
  { slug: "body-fat-calculator", name: "体脂肪率計算機", description: "身長・ウエストなどから米海軍式で体脂肪率を推定します。", category: "calc", componentKey: "body-fat-calculator", keywords: ["体脂肪率"] },
  { slug: "ideal-weight-calculator", name: "適正体重計算機", description: "身長からBMIをもとにした標準体重・適正体重の範囲を計算します。", category: "calc", componentKey: "ideal-weight-calculator", keywords: ["適正体重"] },
  { slug: "pet-age-calculator", name: "ペットの年齢計算機", description: "犬・猫の年齢を人間年齢に換算します。", category: "calc", componentKey: "pet-age-calculator", keywords: ["ペット", "犬", "猫"] },
  { slug: "running-pace-calculator", name: "ランニングペース計算機", description: "距離とタイムからランニングのペースと平均速度を計算します。", category: "calc", componentKey: "running-pace-calculator", keywords: ["ランニング", "ペース"] },
  { slug: "calories-burned-calculator", name: "消費カロリー計算機(運動別)", description: "運動の種類・体重・時間から消費カロリーを推定します。", category: "calc", componentKey: "calories-burned-calculator", keywords: ["消費カロリー"] },
  { slug: "water-intake-calculator", name: "水分摂取量計算機", description: "体重と活動量から1日の目安水分摂取量を計算します。", category: "calc", componentKey: "water-intake-calculator", keywords: ["水分摂取量"] },
  { slug: "prime-checker", name: "素数判定機", description: "入力した整数が素数かどうかを判定します。", category: "calc", componentKey: "prime-checker", keywords: ["素数判定"] },
  { slug: "factorial-calculator", name: "階乗計算機", description: "整数の階乗(n!)を計算します。", category: "calc", componentKey: "factorial-calculator", keywords: ["階乗"] },
  { slug: "logarithm-calculator", name: "対数計算機", description: "指定した底での対数を計算します。", category: "calc", componentKey: "logarithm-calculator", keywords: ["対数", "log"] },
  { slug: "trig-calculator", name: "三角関数計算機", description: "角度からsin・cos・tanの値を計算します。", category: "calc", componentKey: "trig-calculator", keywords: ["三角関数"] },
  { slug: "distance-calculator", name: "2点間の距離計算機", description: "座標平面上の2点間の距離を計算します。", category: "calc", componentKey: "distance-calculator", keywords: ["距離計算"] },
  { slug: "age-gap-calculator", name: "年齢差計算機", description: "2人の生年月日から年齢差を計算します。", category: "calc", componentKey: "age-gap-calculator", keywords: ["年齢差"] },
  { slug: "simple-interest-calculator", name: "単利計算機", description: "元本・利率・期間から単利での利息を計算します。", category: "calc", componentKey: "simple-interest-calculator", keywords: ["単利"] },
  { slug: "tile-flooring-calculator", name: "タイル必要枚数計算機", description: "部屋の面積とタイルのサイズから必要な枚数を計算します。", category: "calc", componentKey: "tile-flooring-calculator", keywords: ["タイル", "床面積"] },
  { slug: "paint-coverage-calculator", name: "ペイント必要量計算機", description: "壁の面積と塗り回数から必要な塗料の量を計算します。", category: "calc", componentKey: "paint-coverage-calculator", keywords: ["ペイント", "塗料"] },

  // --- 単位変換 (9) ---
  { slug: "unit-length", name: "長さ単位変換", description: "メートル・フィート・マイルなど長さの単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "length" }, keywords: ["長さ", "メートル"] },
  { slug: "unit-weight", name: "重さ単位変換", description: "キログラム・ポンドなど重さの単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "weight" }, keywords: ["重さ", "キログラム"] },
  { slug: "unit-temperature", name: "温度単位変換", description: "摂氏・華氏・ケルビンを相互に変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "temperature" }, keywords: ["温度", "摂氏", "華氏"] },
  { slug: "unit-area", name: "面積単位変換", description: "平方メートル・坪・エーカーなど面積の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "area" }, keywords: ["面積", "坪"] },
  { slug: "unit-volume", name: "体積単位変換", description: "リットル・ガロンなど体積の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "volume" }, keywords: ["体積", "リットル"] },
  { slug: "unit-speed", name: "速度単位変換", description: "km/h・m/s・mphなど速度の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "speed" }, keywords: ["速度"] },
  { slug: "unit-time", name: "時間単位変換", description: "秒・分・時間・日など時間の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "time" }, keywords: ["時間の単位"] },
  { slug: "unit-data", name: "データ容量単位変換", description: "バイト・KB・MB・GB・TBを相互に変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "data" }, keywords: ["データ容量", "バイト"] },
  { slug: "unit-pressure", name: "圧力単位変換", description: "パスカル・気圧・バールなど圧力の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "pressure" }, keywords: ["圧力"] },
  { slug: "unit-energy", name: "エネルギー単位変換", description: "ジュール・カロリー・キロワット時などエネルギーの単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "energy" }, keywords: ["エネルギー", "カロリー"] },
  { slug: "unit-power", name: "仕事率単位変換", description: "ワット・馬力など仕事率(パワー)の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "power" }, keywords: ["仕事率", "馬力"] },
  { slug: "unit-angle", name: "角度単位変換", description: "度・ラジアン・グラードなど角度の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "angle" }, keywords: ["角度", "ラジアン"] },
  { slug: "unit-frequency", name: "周波数単位変換", description: "ヘルツ・キロヘルツなど周波数の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "frequency" }, keywords: ["周波数", "ヘルツ"] },
  { slug: "unit-fuel-economy", name: "燃費単位変換", description: "km/L・mpg・L/100kmなど燃費の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "fuel-economy" }, keywords: ["燃費"] },
  { slug: "unit-typography", name: "タイポグラフィ単位変換", description: "px・pt・em・remなどCSSでよく使う単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "typography" }, keywords: ["px", "em", "rem"] },
  { slug: "unit-torque", name: "トルク単位変換", description: "ニュートンメートルなどトルクの単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "torque" }, keywords: ["トルク"] },
  { slug: "unit-density", name: "密度単位変換", description: "kg/m³・g/cm³など密度の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "density" }, keywords: ["密度"] },
  { slug: "unit-force", name: "力の単位変換", description: "ニュートン・重量キログラムなど力の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "force" }, keywords: ["力", "ニュートン"] },
  { slug: "unit-data-transfer-rate", name: "データ転送速度単位変換", description: "bps・Mbps・MB/sなどデータ転送速度の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "data-transfer-rate" }, keywords: ["データ転送速度"] },
  { slug: "unit-illuminance", name: "照度単位変換", description: "ルクス・フットキャンドルなど照度の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "illuminance" }, keywords: ["照度", "ルクス"] },
  { slug: "unit-angular-velocity", name: "角速度単位変換", description: "rad/s・rpmなど角速度の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "angular-velocity" }, keywords: ["角速度"] },
  { slug: "unit-flow-rate", name: "流量単位変換", description: "L/min・m³/hなど流量の単位を変換します。", category: "unit", componentKey: "unit-converter", config: { unit: "flow-rate" }, keywords: ["流量"] },

  // --- 日付・時間 (7) ---
  { slug: "timestamp-converter", name: "タイムスタンプ変換", description: "Unixタイムスタンプと日時を相互に変換します。", category: "datetime", componentKey: "timestamp-converter", keywords: ["unix timestamp", "エポック秒"] },
  { slug: "date-diff", name: "日付差分計算", description: "2つの日付の間の日数・週数・年数を計算します。", category: "datetime", componentKey: "date-diff-calculator", keywords: ["日数計算"] },
  { slug: "weekday-calculator", name: "曜日計算", description: "指定した日付の曜日を調べます。", category: "datetime", componentKey: "weekday-calculator", keywords: ["曜日"] },
  { slug: "countdown-timer", name: "カウントダウンタイマー", description: "指定した秒数からカウントダウンするタイマーです。", category: "datetime", componentKey: "countdown-timer", keywords: ["タイマー"] },
  { slug: "stopwatch", name: "ストップウォッチ", description: "経過時間を計測するストップウォッチです。", category: "datetime", componentKey: "stopwatch", keywords: ["ストップウォッチ"] },
  { slug: "pomodoro-timer", name: "ポモドーロタイマー", description: "作業と休憩を繰り返すポモドーロテクニック用タイマーです。", category: "datetime", componentKey: "pomodoro-timer", keywords: ["ポモドーロ"] },
  { slug: "world-clock", name: "世界時計", description: "世界の主要都市の現在時刻を一覧表示します。", category: "datetime", componentKey: "world-clock", keywords: ["世界時計", "タイムゾーン"] },
  { slug: "eto-calculator", name: "干支計算機", description: "西暦年から十二支(干支)を調べます。", category: "datetime", componentKey: "eto-calculator", keywords: ["干支", "十二支"] },
  { slug: "zodiac-sign-checker", name: "星座判定機", description: "誕生日から星座(12星座)を判定します。", category: "datetime", componentKey: "zodiac-sign-checker", keywords: ["星座"] },
  { slug: "era-year-converter", name: "元号⇔西暦変換", description: "日本の元号(令和・平成など)と西暦を相互に変換します。", category: "datetime", componentKey: "era-year-converter", keywords: ["元号", "令和", "平成"] },
  { slug: "iso-week-number", name: "ISO週番号計算機", description: "指定した日付のISO 8601週番号を計算します。", category: "datetime", componentKey: "iso-week-number-calculator", keywords: ["iso週番号"] },
  { slug: "next-leap-year", name: "次のうるう年計算機", description: "指定した年の次のうるう年を計算します。", category: "datetime", componentKey: "next-leap-year-calculator", keywords: ["うるう年"] },
  { slug: "business-days-calculator", name: "労働日数計算機", description: "2つの日付間の土日を除いた平日日数を計算します。", category: "datetime", componentKey: "business-days-calculator", keywords: ["労働日数", "平日"] },
  { slug: "timezone-diff-calculator", name: "時差計算機", description: "2つの都市間の現在の時差を計算します。", category: "datetime", componentKey: "timezone-diff-calculator", keywords: ["時差"] },

  // --- 色・デザイン (7) ---
  { slug: "color-converter", name: "カラーコード変換", description: "HEX・RGB・HSLのカラーコードを相互に変換します。", category: "color", componentKey: "color-converter", keywords: ["hex", "rgb", "hsl"] },
  { slug: "color-palette", name: "カラーパレット生成", description: "基準となる色から調和のとれたカラーパレットを生成します。", category: "color", componentKey: "color-palette-generator", keywords: ["配色", "パレット"] },
  { slug: "gradient-generator", name: "グラデーション生成", description: "2色以上を指定してCSSグラデーションを生成します。", category: "color", componentKey: "gradient-generator", keywords: ["gradient", "css"] },
  { slug: "contrast-checker", name: "コントラスト比チェッカー", description: "2色のコントラスト比を計算し、WCAG基準を満たすか確認します。", category: "color", componentKey: "contrast-checker", keywords: ["contrast", "wcag"] },
  { slug: "random-color", name: "ランダムカラー生成", description: "ランダムな色を生成します。", category: "color", componentKey: "random-color-generator", keywords: ["ランダムカラー"] },
  { slug: "box-shadow-generator", name: "box-shadowジェネレーター", description: "CSSのbox-shadowプロパティをプレビューしながら生成します。", category: "color", componentKey: "box-shadow-generator", keywords: ["box-shadow", "css"] },
  { slug: "border-radius-generator", name: "border-radiusジェネレーター", description: "CSSのborder-radiusプロパティをプレビューしながら生成します。", category: "color", componentKey: "border-radius-generator", keywords: ["border-radius", "css"] },
  { slug: "nearest-color-name", name: "近似色名検索", description: "指定した色に最も近い色名を検索します。", category: "color", componentKey: "nearest-color-name-finder", keywords: ["色名", "近似色"] },
  { slug: "tailwind-palette-reference", name: "Tailwindカラーパレット参照", description: "Tailwind CSSのデフォルトカラーパレットを一覧表示します。", category: "color", componentKey: "palette-reference", config: { palette: "tailwind" }, keywords: ["tailwind", "カラーパレット"] },
  { slug: "material-palette-reference", name: "Material Designカラーパレット参照", description: "Material Designのカラーパレットを一覧表示します。", category: "color", componentKey: "palette-reference", config: { palette: "material" }, keywords: ["material design", "カラーパレット"] },
  { slug: "color-blend-calculator", name: "カラーブレンド計算機", description: "2色を指定した比率で混ぜ合わせた色を計算します。", category: "color", componentKey: "color-blend-calculator", keywords: ["色混合", "ブレンド"] },
  { slug: "color-lighten-darken", name: "明度調整ツール", description: "色の明度を明るく・暗く調整します。", category: "color", componentKey: "color-lighten-darken", keywords: ["明度調整"] },
  { slug: "complementary-triad-generator", name: "補色・トライアド配色ジェネレーター", description: "基準の色から補色とトライアド配色を生成します。", category: "color", componentKey: "complementary-triad-generator", keywords: ["補色", "トライアド"] },
  { slug: "css-filter-generator", name: "CSS filterジェネレーター", description: "CSSのfilterプロパティをプレビューしながら生成します。", category: "color", componentKey: "css-filter-generator", keywords: ["css filter"] },

  // --- 開発者ツール (12) ---
  { slug: "json-formatter", name: "JSON整形・バリデーター", description: "JSONの整形(インデント)・圧縮・妥当性チェックを行います。", category: "dev", componentKey: "json-formatter", keywords: ["json", "整形"] },
  { slug: "json-csv", name: "JSON⇔CSV変換", description: "JSON配列とCSVを相互に変換します。", category: "dev", componentKey: "json-csv-converter", keywords: ["json", "csv"] },
  { slug: "json-yaml", name: "JSON⇔YAML変換", description: "JSONとYAMLを相互に変換します。", category: "dev", componentKey: "json-yaml-converter", keywords: ["json", "yaml"] },
  { slug: "css-minifier", name: "CSS Minifier", description: "CSSコードの不要な空白・改行・コメントを削除して圧縮します。", category: "dev", componentKey: "css-minifier", keywords: ["css", "minify"] },
  { slug: "html-minifier", name: "HTML Minifier", description: "HTMLコードの不要な空白・改行・コメントを削除して圧縮します。", category: "dev", componentKey: "html-minifier", keywords: ["html", "minify"] },
  { slug: "js-minifier", name: "JS Minifier", description: "JavaScriptコードのコメントや余分な空白を削除して圧縮します。", category: "dev", componentKey: "js-minifier", keywords: ["javascript", "minify"] },
  { slug: "cron-explainer", name: "Cron式解説", description: "Cron式を入力すると、その意味を日本語で解説します。", category: "dev", componentKey: "cron-explainer", keywords: ["cron", "crontab"] },
  { slug: "markdown-preview", name: "Markdownプレビュー", description: "Markdownを入力するとリアルタイムでHTMLプレビューを表示します。", category: "dev", componentKey: "markdown-preview", keywords: ["markdown"] },
  { slug: "user-agent-parser", name: "User-Agent解析", description: "User-Agent文字列からブラウザ・OS情報を解析します。", category: "dev", componentKey: "user-agent-parser", keywords: ["user agent"] },
  { slug: "unicode-codepoint", name: "Unicodeコードポイント表示", description: "文字のUnicodeコードポイントとUTF-8バイト列を表示します。", category: "dev", componentKey: "unicode-codepoint-viewer", keywords: ["unicode", "コードポイント"] },
  { slug: "xml-formatter", name: "XML整形", description: "XMLをインデント付きで整形します。", category: "dev", componentKey: "xml-formatter", keywords: ["xml"] },
  { slug: "sql-formatter", name: "SQL整形", description: "SQL文を読みやすく整形します。", category: "dev", componentKey: "sql-formatter", keywords: ["sql"] },
  { slug: "gitignore-generator", name: ".gitignoreジェネレーター", description: "言語・環境を選んで.gitignoreファイルを生成します。", category: "dev", componentKey: "gitignore-generator", keywords: ["gitignore", "git"] },
  { slug: "readme-generator", name: "READMEテンプレート生成機", description: "プロジェクト情報を入力してREADME.mdのテンプレートを生成します。", category: "dev", componentKey: "readme-generator", keywords: ["readme", "テンプレート"] },
  { slug: "http-status-lookup", name: "HTTPステータスコード検索", description: "HTTPステータスコードの意味を検索・確認できます。", category: "dev", componentKey: "lookup-table", config: { dataset: "http" }, keywords: ["httpステータス"] },
  { slug: "mime-type-lookup", name: "MIMEタイプ検索", description: "ファイル拡張子からMIMEタイプを検索・確認できます。", category: "dev", componentKey: "lookup-table", config: { dataset: "mime" }, keywords: ["mimeタイプ"] },
  { slug: "http-header-parser", name: "HTTPヘッダー解析ツール", description: "貼り付けたHTTPヘッダーをKey/Valueの表形式で表示します。", category: "dev", componentKey: "http-header-parser", keywords: ["httpヘッダー"] },
  { slug: "meta-tag-generator", name: "Meta/OGPタグジェネレーター", description: "タイトル・説明文などからmetaタグ・OGPタグを生成します。", category: "dev", componentKey: "meta-tag-generator", keywords: ["meta", "ogp"] },
  { slug: "lorem-picsum-generator", name: "プレースホルダー画像URL生成", description: "サイズを指定してプレースホルダー画像のURLを生成します。", category: "dev", componentKey: "lorem-picsum-generator", keywords: ["placeholder", "画像"] },
  { slug: "json-diff", name: "JSON Diff(差分比較)", description: "2つのJSONを比較して差分をハイライト表示します。", category: "dev", componentKey: "json-diff-tool", keywords: ["json diff"] },
  { slug: "csv-table-preview", name: "CSVプレビュー・テーブル表示", description: "CSVデータを見やすい表形式でプレビュー表示します。", category: "dev", componentKey: "csv-table-preview", keywords: ["csv", "テーブル"] },
  { slug: "yaml-formatter", name: "YAML整形・バリデーター", description: "YAMLの整形とバリデーションを行います。", category: "dev", componentKey: "yaml-formatter", keywords: ["yaml"] },
  { slug: "env-file-formatter", name: ".envファイル整形", description: ".env形式のファイルをキー順に並び替えて整形します。", category: "dev", componentKey: "env-file-formatter", keywords: ["env", "環境変数"] },
  { slug: "base64-image-previewer", name: "Base64画像プレビューア", description: "Base64文字列から画像をプレビュー表示します。", category: "dev", componentKey: "base64-image-previewer", keywords: ["base64", "画像プレビュー"] },
  { slug: "css-variable-generator", name: "CSS変数ジェネレーター", description: "名前と値のリストから:root {}のCSS変数定義を生成します。", category: "dev", componentKey: "css-variable-generator", keywords: ["css変数", "custom properties"] },
  { slug: "css-specificity-calculator", name: "CSSセレクタ優先度計算機", description: "CSSセレクタの詳細度(specificity)を計算します。", category: "dev", componentKey: "css-specificity-calculator", keywords: ["specificity", "詳細度"] },
  { slug: "url-parser", name: "URLパーサー", description: "URLをプロトコル・ホスト・パス・クエリなどに分解します。", category: "dev", componentKey: "url-parser", keywords: ["url解析"] },
  { slug: "dummy-data-generator", name: "ダミーデータ生成機", description: "名前・メール・住所などのダミーレコードをJSON/CSVで生成します。", category: "dev", componentKey: "dummy-data-generator", keywords: ["ダミーデータ", "faker"] },

  // --- ランダム・ゲーム (8) ---
  { slug: "dice-roller", name: "サイコロ", description: "指定した個数・面数のサイコロを振ります。", category: "random", componentKey: "dice-roller", keywords: ["サイコロ", "dice"] },
  { slug: "coin-flip", name: "コイントス", description: "コインを投げて表裏をランダムに決めます。", category: "random", componentKey: "coin-flip", keywords: ["コイントス"] },
  { slug: "janken", name: "じゃんけん", description: "コンピューターとじゃんけんで勝負します。", category: "random", componentKey: "janken-game", keywords: ["じゃんけん"] },
  { slug: "lottery-picker", name: "くじ引き(リスト抽選)", description: "リストに入力した候補からランダムに1つ選びます。", category: "random", componentKey: "lottery-picker", keywords: ["抽選", "くじ引き"] },
  { slug: "random-number", name: "乱数生成", description: "指定範囲内のランダムな整数を生成します。", category: "random", componentKey: "random-number-generator", keywords: ["乱数"] },
  { slug: "random-string", name: "ランダム文字列生成", description: "指定した文字種・桁数のランダムな文字列を生成します。", category: "random", componentKey: "random-string-generator", keywords: ["ランダム文字列"] },
  { slug: "password-strength", name: "パスワード強度チェッカー", description: "入力したパスワードの強度を判定します。", category: "random", componentKey: "password-strength-checker", keywords: ["パスワード強度"] },
  { slug: "roulette-picker", name: "順番決めルーレット", description: "リストをランダムな順番に並び替えます。", category: "random", componentKey: "roulette-picker", keywords: ["順番決め", "ルーレット"] },

  // --- 生活・お金 (7) ---
  { slug: "calorie-calculator", name: "カロリー計算機(簡易TDEE)", description: "年齢・性別・活動量から1日の推定消費カロリーを計算します。", category: "life", componentKey: "calorie-calculator", keywords: ["カロリー", "tdee"] },
  { slug: "savings-goal", name: "目標貯金シミュレーター", description: "目標金額までの必要な毎月の貯金額をシミュレーションします。", category: "life", componentKey: "savings-goal-simulator", keywords: ["貯金"] },
  { slug: "discount-calculator", name: "割引計算機", description: "割引率から割引後の価格・割引額を計算します。", category: "life", componentKey: "discount-calculator", keywords: ["割引", "セール"] },
  { slug: "hourly-wage", name: "時給計算機", description: "時給と労働時間から給与を計算します。", category: "life", componentKey: "hourly-wage-calculator", keywords: ["時給"] },
  { slug: "work-hours", name: "労働時間計算機", description: "出勤・退勤時刻と休憩時間から実労働時間を計算します。", category: "life", componentKey: "work-hours-calculator", keywords: ["労働時間", "勤怠"] },
  { slug: "electricity-cost", name: "電気代計算機(簡易)", description: "消費電力と使用時間、電力量単価から電気代の目安を計算します。", category: "life", componentKey: "electricity-cost-calculator", keywords: ["電気代"] },
  { slug: "gasoline-cost", name: "ガソリン代計算機", description: "走行距離・燃費・ガソリン単価から燃料費の目安を計算します。", category: "life", componentKey: "gasoline-cost-calculator", keywords: ["ガソリン代", "燃費"] },
  { slug: "mortgage-down-payment", name: "住宅ローン頭金計算機", description: "物件価格と頭金の割合から頭金額と借入必要額を計算します。", category: "life", componentKey: "mortgage-down-payment-calculator", keywords: ["住宅ローン", "頭金"] },
  { slug: "moving-cost-estimator", name: "引っ越し費用概算計算機", description: "世帯タイプと移動距離から引っ越し費用の目安を計算します。", category: "life", componentKey: "moving-cost-estimator", keywords: ["引っ越し費用"] },
  { slug: "subscription-total", name: "サブスク月額合計計算機", description: "登録中のサブスクリプションの月額・年額合計を計算します。", category: "life", componentKey: "subscription-total-calculator", keywords: ["サブスク", "定額"] },
  { slug: "utility-bill-total", name: "光熱費まとめ計算機", description: "電気・ガス・水道・通信費の月間・年間合計を計算します。", category: "life", componentKey: "utility-bill-total-calculator", keywords: ["光熱費"] },
  { slug: "retirement-savings-simulator", name: "老後資金シミュレーター", description: "毎月の積立額と運用利回りから将来の資産額をシミュレーションします。", category: "life", componentKey: "retirement-savings-simulator", keywords: ["老後資金", "資産形成"] },
  { slug: "household-budget-calculator", name: "家計簿(簡易収支計算機)", description: "月収と支出項目を入力して収支を計算します。", category: "life", componentKey: "household-budget-calculator", keywords: ["家計簿", "収支"] },
  { slug: "shipping-cost-estimator", name: "送料概算計算機", description: "荷物のサイズと重量から宅配便の送料目安を計算します。", category: "life", componentKey: "shipping-cost-estimator", keywords: ["送料", "宅配便"] },

  // --- ミドルゲーム (30) ---
  { slug: "game-2048", name: "2048", description: "数字タイルをスライドさせて合体させ、2048を目指すパズルゲームです。盤面サイズをゲーム内で切り替えられます。", category: "midgame", componentKey: "game-2048", keywords: ["2048", "パズル"] },
  { slug: "game-snake", name: "スネークゲーム", description: "矢印キーでヘビを操作してエサを食べ、壁や自分の体にぶつからないように長く生き延びます。速度やフィールドサイズをゲーム内で切り替えられます。", category: "midgame", componentKey: "game-snake", keywords: ["スネーク", "snake"] },
  { slug: "game-breakout", name: "ブロック崩し", description: "パドルでボールを跳ね返してブロックを全て崩すアクションゲームです。難易度をゲーム内で切り替えられます。", category: "midgame", componentKey: "game-breakout", keywords: ["ブロック崩し", "breakout"] },
  { slug: "game-memory", name: "神経衰弱", description: "カードをめくって同じ絵柄のペアを探すカードマッチングゲームです。21種類のテーマからゲーム内で選べます。", category: "midgame", componentKey: "game-memory", keywords: ["神経衰弱", "カードマッチング"] },
  { slug: "game-typing", name: "タイピングゲーム", description: "制限時間内に表示された単語を正確に入力してスコアを競います。10種類の単語セットからゲーム内で選べます。", category: "midgame", componentKey: "game-typing", keywords: ["タイピング", "typing"] },
  { slug: "game-reversi", name: "リバーシ・オセロ", description: "8×8の盤面でコンピューターと対戦するリバーシ(オセロ)です。CPUの強さをゲーム内で切り替えられます。", category: "midgame", componentKey: "game-reversi", keywords: ["リバーシ", "オセロ", "othello"] },
  { slug: "game-whackamole", name: "もぐらたたき", description: "ランダムに出現するキャラクターを制限時間内にクリックしてスコアを競います。キャラクターや速度をゲーム内で切り替えられます。", category: "midgame", componentKey: "game-whackamole", keywords: ["もぐらたたき", "whack-a-mole"] },
  { slug: "game-meteor-dodge", name: "隕石よけ", description: "左右に動く自機を操作して、降り注ぐ隕石を避け続けるオリジナルの避けゲームです。速度をゲーム内で切り替えられます。", category: "midgame", componentKey: "game-meteor-dodge", keywords: ["隕石よけ", "アクション", "オリジナル"] },
  { slug: "game-quiz", name: "クイズ", description: "国旗・歴史・理科・雑学など59種類のジャンルからゲーム内で選んで挑戦できる5問クイズです。", category: "midgame", componentKey: "quiz-game", keywords: ["クイズ", "雑学", "トリビア"] },
  { slug: "game-scramble", name: "文字並び替えゲーム", description: "動物・食べ物・国名など20種類のカテゴリからゲーム内で選んで遊べる文字並び替え(アナグラム)ゲームです。", category: "midgame", componentKey: "word-scramble-game", keywords: ["文字並び替え", "アナグラム"] },
  { slug: "game-hangman", name: "ハングマン", description: "動物・食べ物・国名など20種類のカテゴリからゲーム内で選んで遊べる文字当てゲームです。", category: "midgame", componentKey: "hangman-game", keywords: ["ハングマン", "文字当て"] },
  { slug: "game-tictactoe", name: "三目並べ", description: "CPU対戦の三目並べ(タイタックトー)です。CPUの強さをゲーム内で切り替えられます。", category: "midgame", componentKey: "tictactoe-game", keywords: ["三目並べ", "tic-tac-toe"] },
  { slug: "game-connect-four", name: "コネクトフォー(四目並べ)", description: "縦・横・斜めに4つ並べたら勝ちのコネクトフォーです。CPUと対戦します。", category: "midgame", componentKey: "connect-four-game", keywords: ["コネクトフォー", "四目並べ"] },
  { slug: "game-reaction-time", name: "反射神経テスト", description: "画面が緑に変わった瞬間にクリックして反応速度を測定します。フライング厳禁モードをゲーム内で切り替えられます。", category: "midgame", componentKey: "reaction-time-test", keywords: ["反射神経", "反応速度"] },
  { slug: "game-number-memory", name: "数字記憶テスト", description: "表示された数字を覚えて入力する記憶力テストです。桁数がどんどん増えていきます。", category: "midgame", componentKey: "number-memory-test", keywords: ["記憶力", "数字記憶"] },
  { slug: "game-simon", name: "カラーメモリーゲーム", description: "光る順番を覚えて同じ順にボタンを押す、記憶力ゲームです。", category: "midgame", componentKey: "simon-game", keywords: ["カラーメモリー", "simon"] },
  { slug: "game-maze", name: "迷路ゲーム", description: "スタートからゴールまで進む迷路ゲームです。迷路の大きさをゲーム内で切り替えられます。", category: "midgame", componentKey: "maze-game", keywords: ["迷路"] },
  { slug: "game-jump-dodge", name: "障害物ジャンプゲーム", description: "スペースキーでジャンプして迫りくる障害物を避け続けるゲームです。", category: "midgame", componentKey: "jump-dodge-game", keywords: ["ジャンプ", "障害物"] },
  { slug: "game-slide-puzzle", name: "スライドパズル", description: "数字を並び替えて完成させるスライドパズルです。3×3〜5×5までゲーム内でサイズを切り替えられます。", category: "midgame", componentKey: "slide-puzzle-game", keywords: ["スライドパズル", "15パズル"] },
  { slug: "game-minesweeper", name: "マインスイーパー", description: "地雷を避けながら全マスを開くマインスイーパーです。初級〜上級までゲーム内で難易度を切り替えられます。", category: "midgame", componentKey: "minesweeper-game", keywords: ["マインスイーパー"] },
  { slug: "game-cps-test", name: "クリック速度テスト(CPS)", description: "5秒間のクリック回数からクリック速度(CPS)を測定します。", category: "midgame", componentKey: "cps-test-game", keywords: ["cps", "クリック速度"] },
  { slug: "game-high-low", name: "ハイ&ローゲーム", description: "次のカードが今のカードより高いか低いかを当てるカードゲームです。", category: "midgame", componentKey: "high-low-game", keywords: ["ハイアンドロー", "カードゲーム"] },
  { slug: "game-slot-machine", name: "スロットゲーム", description: "3つのリールを揃えて遊ぶ、仮想コインを使ったスロットゲームです。", category: "midgame", componentKey: "slot-machine-game", keywords: ["スロット", "カジノ風"] },
  { slug: "game-roulette-number", name: "ルーレット数字当て", description: "数字や色に賭けて回転するルーレットの結果を当てる、仮想コインを使ったゲームです。", category: "midgame", componentKey: "roulette-number-game", keywords: ["ルーレット", "カジノ風"] },
  { slug: "game-blackjack", name: "ブラックジャック", description: "ディーラーと21に近い数字を競う簡易ブラックジャックです。", category: "midgame", componentKey: "blackjack-game", keywords: ["ブラックジャック", "カードゲーム"] },
  { slug: "game-rpsls", name: "拡張じゃんけん(グーチョキパートカゲスポック)", description: "グー・チョキ・パーにトカゲとスポックを加えた5種類のじゃんけんです。", category: "midgame", componentKey: "rpsls-game", keywords: ["じゃんけん", "拡張版"] },
  { slug: "game-bubble-click", name: "色合わせクリックゲーム", description: "指定された色のバブルだけを制限時間内にクリックするゲームです。", category: "midgame", componentKey: "bubble-click-game", keywords: ["色合わせ", "クリックゲーム"] },
  { slug: "game-timing-bar", name: "タイミングストップゲーム", description: "動くバーが緑のゾーンに来た瞬間にストップして高得点を狙うゲームです。", category: "midgame", componentKey: "timing-bar-game", keywords: ["タイミングゲーム"] },
  { slug: "game-number-sequence", name: "数字ならべ論理パズル", description: "数字の並びの規則を見つけて次に来る数字を当てる論理パズルです。", category: "midgame", componentKey: "number-sequence-game", keywords: ["論理パズル", "数列"] },
  { slug: "game-pong", name: "ポン(卓球ゲーム)", description: "マウスでパドルを操作してCPUと対戦する定番のポンゲームです。", category: "midgame", componentKey: "pong-game", keywords: ["ポン", "卓球ゲーム"] },
  { slug: "game-lights-out", name: "ライツアウト", description: "クリックしたマスとその上下左右のライトが切り替わる、全て消灯させたらクリアの論理パズルです。", category: "midgame", componentKey: "lights-out-game", keywords: ["ライツアウト", "論理パズル"] },
  { slug: "game-mini-sudoku", name: "ミニ数独(6×6)", description: "6×6マスの数独(ナンバープレース)です。縦・横・2×3ブロックに1〜6が重複しないように埋めます。", category: "midgame", componentKey: "mini-sudoku-game", keywords: ["数独", "ナンバープレース"] },
  { slug: "game-match3", name: "三消しパズル", description: "隣り合う宝石をスワップして3つ以上並べて消す、連鎖が楽しいマッチ3パズルです。", category: "midgame", componentKey: "match3-game", keywords: ["マッチ3", "パズル"] },
  { slug: "game-block-stacker", name: "落ちものブロックパズル", description: "落ちてくるブロックを操作して横一列を揃えて消す、テトリス風の落ちものパズルです。", category: "midgame", componentKey: "block-stacker-game", keywords: ["テトリス風", "落ちものパズル"] },
  { slug: "game-flappy-bird", name: "フラッピー風フライトゲーム", description: "クリック・タップで羽ばたいて高度を保ち、迫りくる土管の隙間をすり抜け続けるゲームです。", category: "midgame", componentKey: "flappy-game", keywords: ["フラッピー", "アクション"] },
  { slug: "game-sokoban", name: "倉庫番パズル", description: "荷物を押して指定の場所まで運ぶ、頭を使う倉庫番(ソコバン)パズルです。", category: "midgame", componentKey: "sokoban-game", keywords: ["倉庫番", "sokoban", "パズル"] },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return ALL_TOOLS.find((tool) => tool.slug === slug);
}
