export const NAMED_COLORS: { name: string; hex: string }[] = [
  { name: "Black", hex: "#000000" }, { name: "White", hex: "#ffffff" },
  { name: "Red", hex: "#ff0000" }, { name: "Green", hex: "#008000" },
  { name: "Blue", hex: "#0000ff" }, { name: "Yellow", hex: "#ffff00" },
  { name: "Cyan", hex: "#00ffff" }, { name: "Magenta", hex: "#ff00ff" },
  { name: "Gray", hex: "#808080" }, { name: "Silver", hex: "#c0c0c0" },
  { name: "Maroon", hex: "#800000" }, { name: "Olive", hex: "#808000" },
  { name: "Navy", hex: "#000080" }, { name: "Purple", hex: "#800080" },
  { name: "Teal", hex: "#008080" }, { name: "Lime", hex: "#00ff00" },
  { name: "Orange", hex: "#ffa500" }, { name: "Pink", hex: "#ffc0cb" },
  { name: "Brown", hex: "#a52a2a" }, { name: "Gold", hex: "#ffd700" },
  { name: "Indigo", hex: "#4b0082" }, { name: "Violet", hex: "#ee82ee" },
  { name: "Coral", hex: "#ff7f50" }, { name: "Salmon", hex: "#fa8072" },
  { name: "Khaki", hex: "#f0e68c" }, { name: "Turquoise", hex: "#40e0d0" },
  { name: "SkyBlue", hex: "#87ceeb" }, { name: "SteelBlue", hex: "#4682b4" },
  { name: "SlateGray", hex: "#708090" }, { name: "Crimson", hex: "#dc143c" },
  { name: "Chocolate", hex: "#d2691e" }, { name: "Tomato", hex: "#ff6347" },
  { name: "Orchid", hex: "#da70d6" }, { name: "Plum", hex: "#dda0dd" },
  { name: "Lavender", hex: "#e6e6fa" }, { name: "Beige", hex: "#f5f5dc" },
  { name: "Ivory", hex: "#fffff0" }, { name: "Mint", hex: "#98ff98" },
  { name: "ForestGreen", hex: "#228b22" }, { name: "SeaGreen", hex: "#2e8b57" },
  { name: "Charcoal", hex: "#36454f" }, { name: "Peach", hex: "#ffe5b4" },
  { name: "Mustard", hex: "#ffdb58" }, { name: "Burgundy", hex: "#800020" },
  { name: "Mauve", hex: "#e0b0ff" }, { name: "Periwinkle", hex: "#ccccff" },
  { name: "Rose", hex: "#ff007f" }, { name: "Amber", hex: "#ffbf00" },
];
